-- float64_sqrt.vhd

-- Generated using ACDS version 19.2 57

library IEEE;
library altera_fp_functions_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity float64_sqrt is
	port (
		clk    : in  std_logic                     := '0';             --    clk.clk
		areset : in  std_logic                     := '0';             -- areset.reset
		a      : in  std_logic_vector(63 downto 0) := (others => '0'); --      a.a
		q      : out std_logic_vector(63 downto 0)                     --      q.q
	);
end entity float64_sqrt;

architecture rtl of float64_sqrt is
	component float64_sqrt_altera_fp_functions_191_eshpdly_cmp is
		port (
			clk    : in  std_logic                     := 'X';             -- clk
			areset : in  std_logic                     := 'X';             -- reset
			a      : in  std_logic_vector(63 downto 0) := (others => 'X'); -- a
			q      : out std_logic_vector(63 downto 0)                     -- q
		);
	end component float64_sqrt_altera_fp_functions_191_eshpdly_cmp;

	for fp_functions_0 : float64_sqrt_altera_fp_functions_191_eshpdly_cmp
		use entity altera_fp_functions_191.float64_sqrt_altera_fp_functions_191_eshpdly;
begin

	fp_functions_0 : component float64_sqrt_altera_fp_functions_191_eshpdly_cmp
		port map (
			clk    => clk,    --    clk.clk
			areset => areset, -- areset.reset
			a      => a,      --      a.a
			q      => q       --      q.q
		);

end architecture rtl; -- of float64_sqrt
